# Generated by Django 3.2.16 on 2022-12-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
