# Generated by Django 3.2.16 on 2022-12-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20221223_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(default='', verbose_name='Project image link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='promotional_url',
            field=models.URLField(default='', verbose_name='Promotional link'),
            preserve_default=False,
        ),
    ]
