# Generated by Django 3.2.16 on 2022-12-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20221223_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='promotional_url',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
