# Generated by Django 3.2.16 on 2022-12-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20221223_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
